server:
  port: 8000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-server
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/usuario/**
eureka:
  client:
    register-with-eureka: false